export const SERVER_URL = import.meta.env.VITE_API_SERVER_URL as string
export const BASE_SERVER_URL = import.meta.env.VITE_SERVER_URL as string

export const API_URL = {
  root: (url = '') => `${url ? url : ''}`,

  auth: (url = '') => API_URL.root(`/auth${url}`),
  register: () => API_URL.auth('/register'),
  login: () => API_URL.auth('/login'),
  forgotPassword: () => API_URL.auth('/forgot-password'),
  resetPassword: () => API_URL.auth('/reset-password'),
  me: () => API_URL.auth('/me'),
  email: (url = '') => API_URL.auth(`/email${url}`),
  sendVerification: () => API_URL.email(`/send-verification`),
  verify: (id = '', hash = '') => API_URL.email(`/verify/${id}/${hash}`),

  notifications: (url = '') => API_URL.auth(`/notifications${url}`),
  readNotifications: () => API_URL.notifications('/read'),
  logout: () => API_URL.auth('/logout'),

  books: (url = '') => API_URL.root(`/books${url}`),
  getBooks: () => API_URL.books('/'),
  createBook: () => API_URL.books(),
  updateBook: (bookId = '') => API_URL.books(`/${bookId}`),
  deleteBook: (bookId = '') => API_URL.books(`/${bookId}`),
  restoreBook: (bookId = '') => API_URL.books(`/${bookId}/restore`),
  getBookById: (bookId = '') => API_URL.books(`/${bookId}`),
  getBookBySlug: (bookSlug = '') => API_URL.books(`/${bookSlug}`),
  getBookByQuery: () => API_URL.books(`/query`),
  getBookBySlugAndId: (bookSlug = '', bookId = '') => API_URL.books(`/${bookSlug}-${bookId}`),
  getBookReviews: (bookId = '') => API_URL.books(`/${bookId}/reviews`),
  booksReservations: () => API_URL.books(`/reservations`),
  reserveBook: (bookId = '') => API_URL.books(`/${bookId}/reserve`),
  subscribe: (bookId = '') => API_URL.books(`/${bookId}/subscribe`),
  unsubscribe: (bookId = '') => API_URL.books(`/${bookId}/unsubscribe`),
  subscriptions: (url = '') => API_URL.root(`/subscriptions${url}`),
  getUserSubscriptions: (userId = '') => API_URL.subscriptions(`/${userId}`),

  authors: (url = '') => API_URL.root(`/authors${url}`),
  getAuthorBySlug: (slug = '') => API_URL.authors(`/${slug}`),
  getAuthors: () => API_URL.authors('/'),
  getAuthorsByQuery: () => API_URL.authors('/query'),
  createAuthor: () => API_URL.authors(),
  updateAuthor: (authorId = '') => API_URL.authors(`/${authorId}`),
  deleteAuthor: (authorId = '') => API_URL.authors(`/${authorId}`),
  getAuthorById: (authorId = '') => API_URL.authors(`/${authorId}`),
  restoreAuthor: (authorId = '') => API_URL.authors(`/${authorId}/restore`),

  publishers: (url = '') => API_URL.root(`/publishers${url}`),
  getPublishers: () => API_URL.publishers('/'),
  getPublishersByQuery: () => API_URL.publishers('/query'),
  createPublisher: () => API_URL.publishers(),
  updatePublisher: (publisherId = '') => API_URL.publishers(`/${publisherId}`),
  deletePublisher: (publisherId = '') => API_URL.publishers(`/${publisherId}`),
  getPublisherById: (publisherId = '') => API_URL.publishers(`/${publisherId}`),
  getPublisherBySlugAndId: (publisherSlug = '') => API_URL.publishers(`/${publisherSlug}`),
  restorePublisher: (publisherId = '') => API_URL.publishers(`/${publisherId}/restore`),

  categories: (url = '') => API_URL.root(`/categories${url}`),
  getCategories: () => API_URL.categories('/'),
  getCategoriesByQuery: () => API_URL.categories('/query'),
  createCategory: () => API_URL.categories(),
  updateCategory: (categoryId = '') => API_URL.categories(`/${categoryId}`),
  deleteCategory: (categoryId = '') => API_URL.categories(`/${categoryId}`),
  getCategoryById: (categoryId = '') => API_URL.categories(`/${categoryId}`),
  restoreCategory: (categoryId = '') => API_URL.categories(`/${categoryId}/restore`),

  genres: (url = '') => API_URL.root(`/genres${url}`),
  getGenres: () => API_URL.genres('/'),
  createGenre: (genre = '') => API_URL.genres(`/${genre}`),
  updateGenre: (genreId = '') => API_URL.genres(`/${genreId}`),
  attachGenre: (bookId = '') => API_URL.genres(`/attach/${bookId}`),
  detachGenre: (bookId = '') => API_URL.genres(`/detach/${bookId}`),
  deleteGenre: (genreId = '') => API_URL.genres(`/${genreId}`),
  restoreGenre: (genreId = '') => API_URL.genres(`/${genreId}/restore`),

  reviews: (url = '') => API_URL.root(`/reviews${url}`),
  getReviews: () => API_URL.reviews('/'),
  createReview: (bookId = '') => API_URL.books(`/${bookId}/reviews`),
  getReview: (reviewId = '') => API_URL.reviews(`/${reviewId}`),

  reservations: (url = '') => API_URL.root(`/reservations${url}`),
  getReservations: () => API_URL.reservations('/'),
  getUserReservations: (userId = '') => API_URL.reservations(`/user/${userId}`),
  getReservationById: (reservationId = '') => API_URL.reservations(`/${reservationId}`),
  cancelReservation: (reservationId = '') => API_URL.reservations(`/${reservationId}/cancel`),
  cancelExpired: () => API_URL.reservations(`/cancel-expired`),
  issueReservation: (reservationId = '') => API_URL.reservations(`/${reservationId}/issue`),
  acceptReservation: (reservationId = '') => API_URL.reservations(`/${reservationId}/accept`),

  admin: (url = '') => API_URL.root(`/admin${url}`),
  users: (url = '') => API_URL.admin(`/users${url}`),
  getUsers: () => API_URL.users('/'),
  createUsers: () => API_URL.users(),
  getUserById: (userId = '') => API_URL.users(`/${userId}`),
  updateUser: (userId = '') => API_URL.users(`/${userId}`),
  updateUserRole: (userId = '') => API_URL.users(`/role/${userId}`),
  deleteUser: (userId = '') => API_URL.users(`/${userId}`),
  restoreUser: (userId = '') => API_URL.users(`/${userId}/restore`),

  adminAuthors: () => API_URL.admin('/authors'),
  adminBooks: () => API_URL.admin('/books'),
  adminPublishers: () => API_URL.admin('/publishers'),
  adminCategories: () => API_URL.admin('/categories'),
  adminGenres: () => API_URL.admin('/genres'),

  uploadImage: () => API_URL.root('/upload-image'),
}
