export { useGetAuthor } from './api/useGetAuthor'
export { useGetAuthors } from './api/useGetAuthors'
export { useCreateAuthor } from './api/useCreateAuthor'
export { useUpdateAuthor } from './api/useUpdateAuthor'
export { useDeleteAuthor } from './api/useDeleteAuthor'
export { useGetAuthorsByQuery } from './api/useGetAuthorsByQuery'
export { useGetAdminAuthors } from './api/useGetAdminAuthors'
export { authorSchema } from './model/author.schema'
export type { AuthorSchema } from './model/author.schema'
export type { IAuthor, IAuthorParams } from './model/author.types'
export { default as AuthorTable } from './ui/AuthorTable.vue'
